version: '3.4'

services:
  webapiwithbackgroundworker.infrastructure.rabbitmq:        
    image: rabbitmq:3-management-alpine
    container_name: webapiwithbackgroundworker.infrastructure.rabbitmq    
    restart: always
    environment:
     RABBITMQ_DEFAULT_VHOST: "/WebApiWithBackgroundWorker"
    ports:     
      - "15671:15671"
      - "15672:15672"   
      - "5672:5672"
